# Use an official Node.js image as the base image
FROM node:14

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json files into the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your application files
COPY . .

# Set the environment variable for the port
ENV PORT 5500

# Expose the port (optional, helps with local dev)
EXPOSE 5500

# Run the app (this is the correct way to run commands)
CMD ["node", "app.js"]
PORT=5500 node app.js
Flask>=2.2.
opencv-python==4.10.0.84
gunicorn==20.1.0
numpy>=1.21.2,<2.0.0
boto3==1.24.0
Werkzeug>=2.2.0
